### ISSUE TITLE
Minor skin fixes

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira-irmasys#1]
Child of aptiko/irma#10.

1. Remove the "Forum" link.
2. In the footer, add a link to https://www.goodagro.org/.
3. Change the 2017 to 2019 in the copyright notice.

**Comment by kickapoo** [comment]
@aptiko
For  2: 
![Screenshot 2019-01-14 16.21.40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb5ecefcf116d00130c67e7/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7850e37a26cbb179f1162b43434d0eee1e020a17b8eb8339a3e46e75df5a0aead2690c76c46e11acba854eeb57b826de5d99a4fedb1294b7607caddecd5d340c041f83fe5831a79d4ccd5ff448e44556b65e.png)
